// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package client

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AgreeRequestsMessage struct {
	PaymentNumber        int64            `protobuf:"varint,1,opt,name=paymentNumber,proto3" json:"paymentNumber,omitempty"`
	ChannelPayments      *ChannelPayments `protobuf:"bytes,2,opt,name=channelPayments,proto3" json:"channelPayments,omitempty"`
	Amount               int64            `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AgreeRequestsMessage) Reset()         { *m = AgreeRequestsMessage{} }
func (m *AgreeRequestsMessage) String() string { return proto.CompactTextString(m) }
func (*AgreeRequestsMessage) ProtoMessage()    {}
func (*AgreeRequestsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *AgreeRequestsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgreeRequestsMessage.Unmarshal(m, b)
}
func (m *AgreeRequestsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgreeRequestsMessage.Marshal(b, m, deterministic)
}
func (m *AgreeRequestsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreeRequestsMessage.Merge(m, src)
}
func (m *AgreeRequestsMessage) XXX_Size() int {
	return xxx_messageInfo_AgreeRequestsMessage.Size(m)
}
func (m *AgreeRequestsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreeRequestsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AgreeRequestsMessage proto.InternalMessageInfo

func (m *AgreeRequestsMessage) GetPaymentNumber() int64 {
	if m != nil {
		return m.PaymentNumber
	}
	return 0
}

func (m *AgreeRequestsMessage) GetChannelPayments() *ChannelPayments {
	if m != nil {
		return m.ChannelPayments
	}
	return nil
}

func (m *AgreeRequestsMessage) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type UpdateRequestsMessage struct {
	PaymentNumber        int64            `protobuf:"varint,1,opt,name=paymentNumber,proto3" json:"paymentNumber,omitempty"`
	ChannelPayments      *ChannelPayments `protobuf:"bytes,2,opt,name=channelPayments,proto3" json:"channelPayments,omitempty"`
	Amount               int64            `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateRequestsMessage) Reset()         { *m = UpdateRequestsMessage{} }
func (m *UpdateRequestsMessage) String() string { return proto.CompactTextString(m) }
func (*UpdateRequestsMessage) ProtoMessage()    {}
func (*UpdateRequestsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{1}
}

func (m *UpdateRequestsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequestsMessage.Unmarshal(m, b)
}
func (m *UpdateRequestsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequestsMessage.Marshal(b, m, deterministic)
}
func (m *UpdateRequestsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequestsMessage.Merge(m, src)
}
func (m *UpdateRequestsMessage) XXX_Size() int {
	return xxx_messageInfo_UpdateRequestsMessage.Size(m)
}
func (m *UpdateRequestsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequestsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequestsMessage proto.InternalMessageInfo

func (m *UpdateRequestsMessage) GetPaymentNumber() int64 {
	if m != nil {
		return m.PaymentNumber
	}
	return 0
}

func (m *UpdateRequestsMessage) GetChannelPayments() *ChannelPayments {
	if m != nil {
		return m.ChannelPayments
	}
	return nil
}

func (m *UpdateRequestsMessage) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ConfirmRequestsMessage struct {
	PaymentNumber        int64    `protobuf:"varint,1,opt,name=paymentNumber,proto3" json:"paymentNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmRequestsMessage) Reset()         { *m = ConfirmRequestsMessage{} }
func (m *ConfirmRequestsMessage) String() string { return proto.CompactTextString(m) }
func (*ConfirmRequestsMessage) ProtoMessage()    {}
func (*ConfirmRequestsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{2}
}

func (m *ConfirmRequestsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmRequestsMessage.Unmarshal(m, b)
}
func (m *ConfirmRequestsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmRequestsMessage.Marshal(b, m, deterministic)
}
func (m *ConfirmRequestsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmRequestsMessage.Merge(m, src)
}
func (m *ConfirmRequestsMessage) XXX_Size() int {
	return xxx_messageInfo_ConfirmRequestsMessage.Size(m)
}
func (m *ConfirmRequestsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmRequestsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmRequestsMessage proto.InternalMessageInfo

func (m *ConfirmRequestsMessage) GetPaymentNumber() int64 {
	if m != nil {
		return m.PaymentNumber
	}
	return 0
}

type ChannelPayment struct {
	ChannelId            int64    `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelPayment) Reset()         { *m = ChannelPayment{} }
func (m *ChannelPayment) String() string { return proto.CompactTextString(m) }
func (*ChannelPayment) ProtoMessage()    {}
func (*ChannelPayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{3}
}

func (m *ChannelPayment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelPayment.Unmarshal(m, b)
}
func (m *ChannelPayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelPayment.Marshal(b, m, deterministic)
}
func (m *ChannelPayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelPayment.Merge(m, src)
}
func (m *ChannelPayment) XXX_Size() int {
	return xxx_messageInfo_ChannelPayment.Size(m)
}
func (m *ChannelPayment) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelPayment.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelPayment proto.InternalMessageInfo

func (m *ChannelPayment) GetChannelId() int64 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

func (m *ChannelPayment) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ChannelPayments struct {
	ChannelPayments      []*ChannelPayment `protobuf:"bytes,1,rep,name=channelPayments,proto3" json:"channelPayments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChannelPayments) Reset()         { *m = ChannelPayments{} }
func (m *ChannelPayments) String() string { return proto.CompactTextString(m) }
func (*ChannelPayments) ProtoMessage()    {}
func (*ChannelPayments) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{4}
}

func (m *ChannelPayments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelPayments.Unmarshal(m, b)
}
func (m *ChannelPayments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelPayments.Marshal(b, m, deterministic)
}
func (m *ChannelPayments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelPayments.Merge(m, src)
}
func (m *ChannelPayments) XXX_Size() int {
	return xxx_messageInfo_ChannelPayments.Size(m)
}
func (m *ChannelPayments) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelPayments.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelPayments proto.InternalMessageInfo

func (m *ChannelPayments) GetChannelPayments() []*ChannelPayment {
	if m != nil {
		return m.ChannelPayments
	}
	return nil
}

type Result struct {
	PaymentNumber        int64    `protobuf:"varint,1,opt,name=paymentNumber,proto3" json:"paymentNumber,omitempty"`
	Result               bool     `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{5}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetPaymentNumber() int64 {
	if m != nil {
		return m.PaymentNumber
	}
	return 0
}

func (m *Result) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*AgreeRequestsMessage)(nil), "AgreeRequestsMessage")
	proto.RegisterType((*UpdateRequestsMessage)(nil), "UpdateRequestsMessage")
	proto.RegisterType((*ConfirmRequestsMessage)(nil), "ConfirmRequestsMessage")
	proto.RegisterType((*ChannelPayment)(nil), "ChannelPayment")
	proto.RegisterType((*ChannelPayments)(nil), "ChannelPayments")
	proto.RegisterType((*Result)(nil), "Result")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c) }

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x9a, 0xc0, 0xc8, 0x25, 0xe2, 0x98, 0x5e,
	0x94, 0x9a, 0x1a, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x52, 0xec, 0x9b, 0x5a, 0x5c, 0x9c, 0x98,
	0x9e, 0x2a, 0xa4, 0xc2, 0xc5, 0x5b, 0x90, 0x58, 0x99, 0x9b, 0x9a, 0x57, 0xe2, 0x57, 0x9a, 0x9b,
	0x94, 0x5a, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1c, 0x84, 0x2a, 0x28, 0x64, 0xc5, 0xc5, 0x9f,
	0x9c, 0x91, 0x98, 0x97, 0x97, 0x9a, 0x13, 0x00, 0x11, 0x2f, 0x96, 0x60, 0x52, 0x60, 0xd4, 0xe0,
	0x36, 0x12, 0xd0, 0x73, 0x46, 0x15, 0x0f, 0x42, 0x57, 0x28, 0x24, 0xc6, 0xc5, 0x96, 0x98, 0x9b,
	0x5f, 0x9a, 0x57, 0x22, 0xc1, 0x0c, 0x36, 0x1a, 0xca, 0x53, 0x9a, 0xc8, 0xc8, 0x25, 0x1a, 0x5a,
	0x90, 0x92, 0x58, 0x32, 0x88, 0xdc, 0x64, 0xc7, 0x25, 0xe6, 0x9c, 0x9f, 0x97, 0x96, 0x59, 0x94,
	0x4b, 0x96, 0x9b, 0x94, 0xdc, 0xb8, 0xf8, 0x50, 0xed, 0x16, 0x92, 0xe1, 0xe2, 0x84, 0x5a, 0xee,
	0x99, 0x02, 0xd5, 0x83, 0x10, 0x40, 0x72, 0x07, 0x13, 0x8a, 0x3b, 0x7c, 0xb8, 0xf8, 0xd1, 0xfc,
	0x20, 0x64, 0x89, 0xe9, 0x5d, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x7e, 0x34, 0xef, 0x62, 0xf8,
	0x56, 0xc9, 0x8d, 0x8b, 0x2d, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x84, 0xc8, 0x90, 0x15, 0xe3, 0x62,
	0x2b, 0x02, 0xab, 0x07, 0xbb, 0x8a, 0x23, 0x08, 0xca, 0x33, 0x5a, 0xc1, 0xc8, 0xc5, 0xe6, 0x0c,
	0x4e, 0x55, 0x42, 0x26, 0x5c, 0x02, 0x89, 0xa0, 0xe4, 0x04, 0xb6, 0x10, 0x12, 0x54, 0x42, 0xa2,
	0x7a, 0xd8, 0x52, 0x98, 0x14, 0xbb, 0x1e, 0xc4, 0x72, 0x25, 0x06, 0x21, 0x23, 0x2e, 0xde, 0x52,
	0xe4, 0x18, 0x17, 0x12, 0xd3, 0xc3, 0x9a, 0x02, 0x90, 0xf5, 0x98, 0x70, 0xf1, 0x25, 0x43, 0xa2,
	0x04, 0x16, 0xa4, 0xe2, 0x7a, 0xd8, 0xe3, 0x08, 0x49, 0x57, 0x12, 0x1b, 0x38, 0xd9, 0x1b, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xb6, 0x4a, 0x98, 0x06, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientClient is the client API for Client service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientClient interface {
	AgreementRequest(ctx context.Context, in *AgreeRequestsMessage, opts ...grpc.CallOption) (*Result, error)
	UpdateRequest(ctx context.Context, in *UpdateRequestsMessage, opts ...grpc.CallOption) (*Result, error)
	ConfirmPayment(ctx context.Context, in *ConfirmRequestsMessage, opts ...grpc.CallOption) (*Result, error)
}

type clientClient struct {
	cc *grpc.ClientConn
}

func NewClientClient(cc *grpc.ClientConn) ClientClient {
	return &clientClient{cc}
}

func (c *clientClient) AgreementRequest(ctx context.Context, in *AgreeRequestsMessage, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/Client/agreementRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) UpdateRequest(ctx context.Context, in *UpdateRequestsMessage, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/Client/updateRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) ConfirmPayment(ctx context.Context, in *ConfirmRequestsMessage, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/Client/confirmPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServer is the server API for Client service.
type ClientServer interface {
	AgreementRequest(context.Context, *AgreeRequestsMessage) (*Result, error)
	UpdateRequest(context.Context, *UpdateRequestsMessage) (*Result, error)
	ConfirmPayment(context.Context, *ConfirmRequestsMessage) (*Result, error)
}

// UnimplementedClientServer can be embedded to have forward compatible implementations.
type UnimplementedClientServer struct {
}

func (*UnimplementedClientServer) AgreementRequest(ctx context.Context, req *AgreeRequestsMessage) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgreementRequest not implemented")
}
func (*UnimplementedClientServer) UpdateRequest(ctx context.Context, req *UpdateRequestsMessage) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRequest not implemented")
}
func (*UnimplementedClientServer) ConfirmPayment(ctx context.Context, req *ConfirmRequestsMessage) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPayment not implemented")
}

func RegisterClientServer(s *grpc.Server, srv ClientServer) {
	s.RegisterService(&_Client_serviceDesc, srv)
}

func _Client_AgreementRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgreeRequestsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).AgreementRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Client/AgreementRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).AgreementRequest(ctx, req.(*AgreeRequestsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_UpdateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequestsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).UpdateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Client/UpdateRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).UpdateRequest(ctx, req.(*UpdateRequestsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_ConfirmPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequestsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).ConfirmPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Client/ConfirmPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).ConfirmPayment(ctx, req.(*ConfirmRequestsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Client_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Client",
	HandlerType: (*ClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "agreementRequest",
			Handler:    _Client_AgreementRequest_Handler,
		},
		{
			MethodName: "updateRequest",
			Handler:    _Client_UpdateRequest_Handler,
		},
		{
			MethodName: "confirmPayment",
			Handler:    _Client_ConfirmPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client.proto",
}
